---
version: '3.0'

services:
  feedbackbuch-db:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: randomtest1
      POSTGRES_USER: feedbackbuch
      POSTGRES_DB: feedbackbuch
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal

  feedbackbuch-backend:
    build: server
    image: "feedbackbuch-backend:latest"
    ports:
      - "127.0.0.1:8081:8081"
    env_file:
      - server/feedbackbuch-backend.env
    networks:
      - internal
    depends_on:
      - feedbackbuch-db

  feedbackbuch-frontend:
    build: 
      context: frontend
      args: 
        SERVER_HTTP: http://localhost:8081/query
        SERVER_WS: ws://localhost:8081/query
    image: "feedbackbuch-frontend:latest"
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - feedbackbuch-backend

networks:
  internal: {}

volumes:
  db: {}
