---
version: '3.0'

services:
  feedbackbuch-frontend:
    build: frontend
    image: "feedbackbuch-frontend:latest"
    ports:
      - "127.0.0.1:8080:80"
    environment:
      VUE_APP_GRAPHQL_HTTP: http://localhost:8081/query
      VUE_APP_GRAPHQL_WS: ws://localhost:8081/query
    depends_on:
      - feedbackbuch-backend

  feedbackbuch-backend:
    build: server
    image: "feedbackbuch-backend:latest"
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      PORT: 8081
